#!/usr/bin/env bash

if [ "$1" = "-r" ]; then
        REC=1
        DIR="$2"
        if [ "$#" -ge 3 ]; then
                echo "ERROR! Too many operands" 1>&2
                exit 1
        fi
        if [ -z "$2" ]; then
            DIR="."
        fi


else
        REC=0
        DIR="$1"
        if [ "$#" -ge 2 ]; then
                echo "ERROR! Too many operands" 1>&2
                exit 1
        fi
fi


if [ -z "$1" ]; then
    DIR="."
fi


if [[ "$DIR" =~ ^- ]]; then
        echo "ERROR! First character is -" 1>&2
        exit 1
fi


if [ ! -d "$DIR" ]; then
        echo "ERROR! not a directory" 1>&2
        exit 1
fi


if [ -L "$DIR" ]; then
    echo "ERROR! not a directory" 1>&2
    exit 1
fi

 


noRecursion(){

    badASCII=$(find "$DIR" -mindepth 1 -maxdepth 1 |
		   grep -Ev "\/[A-Za-z._-]{0,14}$")
    periodNames=$(find "$DIR" -mindepth 1 -maxdepth 1|
		      grep -E "^\.[/A-za-z_-]|^\.{2}[/A-za-z_-]|^-")
    repeatNames=$(find "$DIR" -mindepth 1 -maxdepth 1| sort -f | uniq -iD)

    POOR="$badASCII"
    POOR+="$periodNames"
    POOR+=$'\n'
    POOR+="$repeatNames"
    
    echo "$POOR" | sort -u | sed '/^$/d' 
}


if [ "$REC" -eq 1 ]; then
    find "${DIR}" -type d -exec ${0} {} \;
else
    noRecursion $DIR
fi



